name: gridtest2
favicon: null
layout_spectrum: 0.21290883794426918
typography_spectrum: 0.8857213754672557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4399827313609421
  lightness: 0.9374672463163733
  saturation: 0.4206964457407594
  rhythmicContrast: 0.20512038539163768
purpose: []
